"use client";
import { DollarSign, TrendingDown, Shield, Leaf } from "lucide-react";
import { motion } from "framer-motion";

// Industry constants
const DEMURRAGE_PER_DAY = 45000;     // USD per ship per day
const CARBON_CREDIT_PER_TON = 65;   // USD per metric ton CO2
const CARGO_PROTECTION_RATE = 0.08; // 8% of cargo value recovered by timely reroute

export default function SavingsPanel({ state, metrics }: { state: any; metrics: any }) {
  const ships = state?.ships || [];
  const reroutedShips = ships.filter((s: any) => s.status === "rerouted");
  const co2Saved = state?.total_co2_saved_tons || 0;
  const totalAlerts = metrics?.total_alerts_resolved || 0;

  const delayCostSaved = totalAlerts * 2.5 * DEMURRAGE_PER_DAY; // avg 2.5 days saved per reroute
  const carbonRevenue = co2Saved * CARBON_CREDIT_PER_TON;
  const cargoProtected = reroutedShips.reduce((sum: number, s: any) => sum + (s.cargo_value_usd || 0) * CARGO_PROTECTION_RATE, 0);
  const totalSavings = delayCostSaved + carbonRevenue + cargoProtected;

  const items = [
    {
      label: "Delay Cost Avoided",
      value: delayCostSaved,
      icon: TrendingDown,
      color: "text-blue-400",
      bg: "bg-blue-500/10",
      border: "border-blue-500/20",
      sub: `${totalAlerts} routes optimized × 2.5 days avg`,
    },
    {
      label: "Carbon Credits Earned",
      value: carbonRevenue,
      icon: Leaf,
      color: "text-emerald-400",
      bg: "bg-emerald-500/10",
      border: "border-emerald-500/20",
      sub: `${co2Saved.toLocaleString()} tons × $${CARBON_CREDIT_PER_TON}/ton`,
    },
    {
      label: "Cargo Protected",
      value: cargoProtected,
      icon: Shield,
      color: "text-purple-400",
      bg: "bg-purple-500/10",
      border: "border-purple-500/20",
      sub: `${reroutedShips.length} vessels rerouted in time`,
    },
    {
      label: "Total Value Generated",
      value: totalSavings,
      icon: DollarSign,
      color: "text-yellow-400",
      bg: "bg-yellow-500/10",
      border: "border-yellow-500/20",
      sub: "Combined economic impact today",
      highlight: true,
    },
  ];

  const fmt = (v: number) => v >= 1e6 ? `$${(v/1e6).toFixed(2)}M` : v >= 1e3 ? `$${(v/1e3).toFixed(0)}K` : `$${v.toFixed(0)}`;

  return (
    <div className="glass-panel rounded-2xl overflow-hidden">
      <div className="px-5 py-4 border-b border-white/8 bg-gradient-to-r from-yellow-900/40 via-yellow-900/10 to-transparent">
        <h3 className="text-sm font-bold text-white flex items-center gap-2">
          <DollarSign size={16} className="text-yellow-400" /> <span className="gradient-text-warm">AI Economic Impact</span>
        </h3>
        <p className="text-[11px] text-gray-400 mt-1">Real-dollar value generated by AI optimizations today</p>
      </div>
      <div className="p-4 grid grid-cols-2 md:grid-cols-4 gap-3">
        {items.map((item, i) => (
          <motion.div
            key={item.label}
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.07 }}
            className={`rounded-xl p-4 border ${item.border} ${item.bg} ${item.highlight ? "col-span-2 md:col-span-1" : ""}`}
          >
            <div className={`p-2.5 rounded-xl ${item.bg} ${item.color} w-fit mb-3 shadow-inner border border-white/5`}>
              <item.icon size={20} />
            </div>
            <p className="text-[10px] text-gray-400 font-bold uppercase tracking-widest mb-1.5">{item.label}</p>
            <p className={`text-3xl font-black ${item.color} font-data`}>{fmt(item.value)}</p>
            <p className="text-[11px] font-medium text-gray-500 mt-1.5">{item.sub}</p>
          </motion.div>
        ))}
      </div>
    </div>
  );
}
