"use client";
import { useState, useCallback } from "react";
import NavBar from "@/components/NavBar";
import ChatWidget from "@/components/ChatWidget";
import { apiFetch } from "@/lib/api";
import { motion, AnimatePresence } from "framer-motion";
import { Zap, RefreshCw, Printer, TrendingUp, AlertTriangle, DollarSign, Leaf, Bot, Clock, ChevronRight } from "lucide-react";

type Section = { icon: string; title: string; content: string; color: string };

function parseBriefing(raw: string): Section[] {
  // Try to extract structured sections from Gemini output
  const sections = [
    { icon: "📊", title: "Fleet Status Overview", color: "#3b82f6" },
    { icon: "⚠️", title: "Top 3 Risk Alerts", color: "#ef4444" },
    { icon: "💰", title: "Financial Impact", color: "#10b981" },
    { icon: "🌱", title: "Sustainability Metrics", color: "#a855f7" },
    { icon: "🤖", title: "AI Recommendation", color: "#f59e0b" },
  ];

  // Split raw text into sections
  const lines = raw.split("\n").filter(l => l.trim());
  const chunks: string[][] = [[], [], [], [], []];
  let current = 0;
  for (const line of lines) {
    const lower = line.toLowerCase();
    if (lower.includes("risk") || lower.includes("alert") || lower.includes("warning")) current = 1;
    else if (lower.includes("financ") || lower.includes("cost") || lower.includes("saving") || lower.includes("$")) current = 2;
    else if (lower.includes("co2") || lower.includes("carbon") || lower.includes("sustainability") || lower.includes("esg")) current = 3;
    else if (lower.includes("recommend") || lower.includes("action") || lower.includes("suggest")) current = 4;
    chunks[current].push(line);
  }

  return sections.map((s, i) => ({
    ...s,
    content: chunks[i].join("\n").trim() || (i === 0 ? raw.slice(0, 200) : "No data for this section."),
  }));
}

export default function BriefingPage() {
  const [briefing, setBriefing] = useState<Section[] | null>(null);
  const [raw, setRaw] = useState("");
  const [loading, setLoading] = useState(false);
  const [generatedAt, setGeneratedAt] = useState<Date | null>(null);

  const generate = useCallback(async () => {
    setLoading(true);
    setBriefing(null);
    try {
      const [metricsRes, fleetRes, logRes] = await Promise.all([
        apiFetch("/metrics"),
        apiFetch("/fleet"),
        apiFetch("/optimization-log"),
      ]);
      const ships = fleetRes?.ships || [];
      const log = logRes || [];
      const atRisk = ships.filter((s: any) => s.status !== "on-time" && s.status !== "rerouted").length;
      const totalValue = ships.reduce((s: number, v: any) => s + (v.cargo_value_usd || 0), 0);
      const co2 = log.reduce((s: number, l: any) => s + (l.co2_saved || 0), 0);

      const prompt = `You are the Chief AI Officer of a global maritime supply chain company. Generate a professional daily executive briefing for today: ${new Date().toDateString()}.

LIVE DATA:
- Fleet: ${ships.length} vessels (${atRisk} at risk, ${ships.filter((s:any)=>s.status==="rerouted").length} rerouted by AI)
- Total cargo value: $${(totalValue/1e6).toFixed(0)}M under management
- AI optimizations today: ${log.length}
- CO₂ prevented: ${co2}t

Structure your briefing with these exact headers:
📊 FLEET STATUS OVERVIEW
⚠️ TOP 3 RISK ALERTS
💰 FINANCIAL IMPACT
🌱 SUSTAINABILITY METRICS
🤖 AI RECOMMENDATION

Be specific with numbers, executive-level in tone, and under 300 words total.`;

      const res = await apiFetch("/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ query: prompt }) });
      const text = res.reply || "";
      setRaw(text);
      setBriefing(parseBriefing(text));
      setGeneratedAt(new Date());
    } catch {
      setBriefing([{ icon: "⚠️", title: "Error", content: "Could not generate briefing. Check backend connection.", color: "#ef4444" }]);
    }
    setLoading(false);
  }, []);

  return (
    <div className="min-h-screen flex flex-col">
      <NavBar />
      <main className="flex-1 max-w-4xl mx-auto w-full px-4 md:px-8 py-8 flex flex-col gap-6">
        <div className="flex items-center justify-between flex-wrap gap-4">
          <div>
            <h1 className="text-3xl font-black text-white flex items-center gap-3"><Bot size={26} className="text-purple-400"/> AI Daily Briefing</h1>
            <p className="text-gray-500 mt-1">Executive-level fleet intelligence generated by Gemini 2.0 Flash</p>
          </div>
          <div className="flex gap-2">
            {briefing && (
              <button onClick={() => window.print()} className="flex items-center gap-1.5 px-4 py-2 rounded-xl border border-white/10 bg-white/5 text-xs font-bold text-gray-300 hover:text-white hover:bg-white/10 transition-all">
                <Printer size={13}/> Print
              </button>
            )}
            <button onClick={generate} disabled={loading}
              className="flex items-center gap-2 px-5 py-2.5 rounded-xl font-bold text-sm text-white disabled:opacity-60 transition-all"
              style={{ background: "linear-gradient(135deg, #a855f7, #6366f1)", boxShadow: "0 8px 30px rgba(168,85,247,0.3)" }}>
              {loading ? <><RefreshCw size={14} className="animate-spin"/> Generating...</> : <><Zap size={14}/> {briefing ? "Regenerate" : "Generate Today's Briefing"}</>}
            </button>
          </div>
        </div>

        {/* Date header */}
        {generatedAt && (
          <div className="flex items-center gap-3 text-xs text-gray-500">
            <Clock size={11}/> Generated {generatedAt.toLocaleString()} · Powered by Gemini 2.0 Flash
          </div>
        )}

        <AnimatePresence mode="wait">
          {loading && (
            <motion.div key="load" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
              className="glass-panel rounded-2xl p-12 flex flex-col items-center gap-4">
              <div className="relative w-16 h-16">
                <div className="absolute inset-0 border-2 border-purple-500/20 rounded-full animate-spin border-t-purple-400"/>
                <div className="absolute inset-2 border-2 border-blue-500/20 rounded-full animate-spin border-t-blue-400" style={{ animationDirection: "reverse", animationDuration: "0.7s" }}/>
              </div>
              <p className="text-sm text-gray-500">Gemini analyzing live fleet telemetry...</p>
              <div className="flex gap-6 text-xs text-gray-700">
                {["Loading fleet data", "Calculating risk scores", "Generating insights"].map((t, i) => (
                  <span key={t} className="flex items-center gap-1.5 animate-pulse" style={{ animationDelay: `${i * 0.4}s` }}>
                    <span className="w-1.5 h-1.5 rounded-full bg-purple-500"/>
                    {t}
                  </span>
                ))}
              </div>
            </motion.div>
          )}

          {briefing && !loading && (
            <motion.div key="result" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="flex flex-col gap-4">
              {briefing.map((section, i) => (
                <motion.div key={section.title} initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: i * 0.1 }}
                  className="glass-panel rounded-2xl p-5 border"
                  style={{ borderColor: section.color + "25" }}>
                  <div className="flex items-center gap-2.5 mb-3">
                    <span className="text-xl">{section.icon}</span>
                    <h2 className="text-sm font-black text-white">{section.title}</h2>
                    <div className="h-px flex-1 rounded-full" style={{ background: section.color + "30" }}/>
                  </div>
                  <div className="text-sm text-gray-400 leading-relaxed whitespace-pre-wrap">
                    {section.content}
                  </div>
                </motion.div>
              ))}

              <div className="glass-panel rounded-xl p-4 border border-emerald-500/20 text-center">
                <p className="text-[10px] text-emerald-400 font-bold uppercase tracking-widest mb-1">CLASSIFICATION</p>
                <p className="text-xs text-gray-400">CONFIDENTIAL · For Executive Distribution Only · Smart Supply Chain AI v2.0</p>
              </div>
            </motion.div>
          )}

          {!briefing && !loading && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}
              className="glass-panel rounded-2xl p-16 flex flex-col items-center gap-4 text-center border border-dashed border-white/10">
              <Bot size={48} className="text-gray-700"/>
              <p className="text-base text-gray-500 font-semibold">Ready to generate today's executive briefing</p>
              <p className="text-xs text-gray-700">Gemini will analyze live fleet data, risks, savings, and sustainability metrics</p>
              <button onClick={generate}
                className="flex items-center gap-2 px-6 py-3 rounded-xl font-bold text-sm text-white mt-2"
                style={{ background: "linear-gradient(135deg, #a855f7, #6366f1)" }}>
                <Zap size={14}/> Generate Briefing
              </button>
            </motion.div>
          )}
        </AnimatePresence>
      </main>
      <ChatWidget />
    </div>
  );
}
